name: gandb_care_clinic
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.1.6
  google_fonts: ^6.1.0
  http: ^1.6.0
  url_launcher: ^6.2.6
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.7
  add_2_calendar: ^3.0.1
  share_plus: ^10.1.4
  audioplayers: ^6.6.0
  intl: ^0.19.0
  firebase_core: ^4.9.0
  firebase_crashlytics: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - .env

# 👇 KONFIGURASI SPLASH SCREEN WAJIB DI SINI (Di Luar Dependencies) 👇
flutter_native_splash:
  color: "#FFFFFF"
  # Kalau lu udah punya file logo PNG, hapus tanda '#' di bawah ini dan arahin ke foldernya:
  # image: assets/logo_klinik.png 
  android_12:
    color: "#FFFFFF"
    # image: assets/logo_klinik.png